/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as WhiteboardRouteImport } from './routes/whiteboard'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DataRouteImport } from './routes/data'
import { Route as CodeRouteImport } from './routes/code'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiYoutubeRouteImport } from './routes/api/youtube'

const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const WhiteboardRoute = WhiteboardRouteImport.update({
  id: '/whiteboard',
  path: '/whiteboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeRoute = ApiYoutubeRouteImport.update({
  id: '/api/youtube',
  path: '/api/youtube',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/code': typeof CodeRoute
  '/data': typeof DataRoute
  '/docs': typeof DocsRoute
  '/graph': typeof GraphRoute
  '/whiteboard': typeof WhiteboardRoute
  '/youtube': typeof YoutubeRoute
  '/api/youtube': typeof ApiYoutubeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/code': typeof CodeRoute
  '/data': typeof DataRoute
  '/docs': typeof DocsRoute
  '/graph': typeof GraphRoute
  '/whiteboard': typeof WhiteboardRoute
  '/youtube': typeof YoutubeRoute
  '/api/youtube': typeof ApiYoutubeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/code': typeof CodeRoute
  '/data': typeof DataRoute
  '/docs': typeof DocsRoute
  '/graph': typeof GraphRoute
  '/whiteboard': typeof WhiteboardRoute
  '/youtube': typeof YoutubeRoute
  '/api/youtube': typeof ApiYoutubeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audio'
    | '/code'
    | '/data'
    | '/docs'
    | '/graph'
    | '/whiteboard'
    | '/youtube'
    | '/api/youtube'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audio'
    | '/code'
    | '/data'
    | '/docs'
    | '/graph'
    | '/whiteboard'
    | '/youtube'
    | '/api/youtube'
  id:
    | '__root__'
    | '/'
    | '/audio'
    | '/code'
    | '/data'
    | '/docs'
    | '/graph'
    | '/whiteboard'
    | '/youtube'
    | '/api/youtube'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioRoute: typeof AudioRoute
  CodeRoute: typeof CodeRoute
  DataRoute: typeof DataRoute
  DocsRoute: typeof DocsRoute
  GraphRoute: typeof GraphRoute
  WhiteboardRoute: typeof WhiteboardRoute
  YoutubeRoute: typeof YoutubeRoute
  ApiYoutubeRoute: typeof ApiYoutubeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whiteboard': {
      id: '/whiteboard'
      path: '/whiteboard'
      fullPath: '/whiteboard'
      preLoaderRoute: typeof WhiteboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube': {
      id: '/api/youtube'
      path: '/api/youtube'
      fullPath: '/api/youtube'
      preLoaderRoute: typeof ApiYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioRoute: AudioRoute,
  CodeRoute: CodeRoute,
  DataRoute: DataRoute,
  DocsRoute: DocsRoute,
  GraphRoute: GraphRoute,
  WhiteboardRoute: WhiteboardRoute,
  YoutubeRoute: YoutubeRoute,
  ApiYoutubeRoute: ApiYoutubeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
